<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>niny</string>
	</array>
	<key>foldingStartMarker</key>
	<string>do\s*$|/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>end\s*$|\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>Niny</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.niny</string>
                </dict>
                <key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.niny</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(macro)\s(.*)\s(do)\s*$</string>
			<key>name</key>
			<string>meta.function.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|do|end)\b</string>
			<key>name</key>
			<string>keyword.control.niny</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.niny</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$).*$\n?</string>
			<key>name</key>
			<string>comment.line.dollar-sign.niny</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.niny</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.niny</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.niny</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.niny</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.niny</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x[0-9A-Fa-f]{2}|[0-2][0-7]{0,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.niny</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(full|push|dump|dup|pop|swp|change|rev|len|memory|add|sub|mult|div|pow|root|divmod|if|or|and|not|type|int|bool|float|string|list|append|insert|id|flat|inp|get)\b</string>
			<key>name</key>
			<string>support.function.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,[ |\t]*</string>
			<key>name</key>
			<string>meta.delimiter.object.comma.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|\$|%|&amp;|\*|\-\-|\-|\+\+|\+|~|===|==|=|!=|!==|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\|\||\?\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|\^=|\b(or|and|not|del)\b</string>
			<key>name</key>
			<string>keyword.operator.niny</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.niny</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nn</string>
	<key>uuid</key>
	<string>46DDC982-5C78-5543-BC99-85A3BB6CD6F3</string>
</dict>
</plist>
